export const formFields = (roleData) => [
  {
    name: "vaccineDetails",
    label: "Vaccine Details",
    type: "multiFields",
    templateRows: "repeat(1, 1fr)",
    templateColumns: "repeat(5, 1fr)",
    fields: [
      {
        name: "name",
        label: "Name",
        placeholder: "Name",
        type: "text",
        colSpan: 1,
        rowSpan: 1,
      },
      {
        name: "description",
        label: "Description",
        placeholder: "Description",
        type: "text",
        colSpan: 1,
        rowSpan: 1,
      },
      {
        name: "range",
        label: "Range",
        placeholder: "Range",
        type: "text",
        colSpan: 1,
        rowSpan: 1,
      },
      {
        name: "isMandatory",
        label: "Is Mandatory",
        type: "checkbox",
        colSpan: 1,
        rowSpan: 1,
      },
      {
        name: "timePeriod",
        label: "Time Period",
        placeholder: "Time Period",
        type: "select",
        colSpan: 1,
        rowSpan: 1,
        options: [
          { value: "days", label: "Days" },
          { value: "week", label: "Weekly" },
          { value: "month", label: "Monthly" },
          // { value: "year", label: "Yearly" },
        ],
        // checkConditions: ["month", "4"],
        isCondition: true,
        shoWhen: [
          { timePeriod: "month" },
          { timePeriod: "week" },
          { timePeriod: "days" },
          // { timePeriod: "yearly" },
        ],
        conditionFields: [
          {
            name: "month",
            label: "Month",
            placeholder: "Month",
            type: "select",
            colSpan: 2,
            rowSpan: 1,
            options: [
              { value: "january", label: "January" },
              { value: "february", label: "February" },
              { value: "march", label: "March" },
              { value: "april", label: "April" },
              { value: "may", label: "May" },
              { value: "june", label: "June" },
              { value: "july", label: "July" },
              { value: "august", label: "August" },
              { value: "september", label: "September" },
              { value: "october", label: "October" },
              { value: "november", label: "November" },
              { value: "december", label: "December" },
            ],
          },
          {
            name: "week",
            label: "Week",
            placeholder: "Week",
            type: "select",
            colSpan: 2,
            rowSpan: 1,
            options: [
              { value: "week1", label: "Week 1" },
              { value: "week2", label: "Week 2" },
              { value: "week3", label: "Week 3" },
              { value: "week4", label: "Week 4" },
            ],
          },
          {
            name: "days",
            label: "Days",
            placeholder: "Days",
            type: "text",
            colSpan: 2,
            rowSpan: 1,
          },
        ],
      },
    ],
  },
];
