export const formFields = (roleData) => [
  {
    name: "vaccineDetails",
    label: "Vaccine Details",
    type: "multiFields",
    templateRows: "repeat(1, 1fr)",
    templateColumns: "repeat(5, 1fr)",
    fields: [
      {
        name: "name",
        label: "Name",
        placeholder: "Name",
        type: "text",
        colSpan: 1,
        rowSpan: 1,
      },
      {
        name: "description",
        label: "Description",
        placeholder: "Description",
        type: "text",
        colSpan: 1,
        rowSpan: 1,
      },
      {
        name: "range",
        label: "Range",
        placeholder: "Range",
        type: "text",
        colSpan: 1,
        rowSpan: 1,
      },
      {
        name: "is_mandatory",
        label: "Is Mandatory",
        type: "checkbox",
        colSpan: 1,
        rowSpan: 1,
      },
      {
        name: "timePeriod",
        label: "Time Period",
        placeholder: "Time Period",
        type: "select",
        colSpan: 1,
        rowSpan: 1,
        options: [
          { value: "days", label: "Days" },
          { value: "week", label: "Weekly" },
          { value: "month", label: "Monthly" },
          // { value: "year", label: "Yearly" },
        ],
        // checkConditions: ["month", "4"],
        isCondition: true,
        shoWhen: [
          { timePeriod: "month" },
          { timePeriod: "week" },
          { timePeriod: "days" },
          // { timePeriod: "yearly" },
        ],
        conditionFields: [
          {
            name: "month",
            label: "Month",
            placeholder: "Month",
            type: "select",
            colSpan: 2,
            rowSpan: 1,
            isExternal: true,
            extra: {
              slug: "month",
            },
            // options: ,
          },
          {
            name: "week",
            label: "Week",
            placeholder: "Week",
            type: "select",
            colSpan: 2,
            rowSpan: 1,
            isExternal: true,
            extra: {
              slug: "week",
            },
            // options: ,
          },
          {
            name: "days",
            label: "Days",
            placeholder: "Days",
            type: "text",
            colSpan: 2,
            rowSpan: 1,
          },
        ],
      },
    ],
  },
];
