export const GET_USER_ROLE = "GET_USER_ROLE";
export const GET_USER_ROLE_SUCCESS = "GET_USER_ROLE_SUCCESS";
export const GET_USER_ROLE_FAIL = "GET_USER_ROLE_FAIL";
export const UPDATE_ROLES_LOADER = "UPDATE_ROLES_LOADER";
