export const GET_USER_ROLES = "GET_USER_ROLES";
export const GET_USER_ROLE_SUCCESS = "GET_USER_ROLE_SUCCESS";
export const GET_USER_ROLE_API_FAIL = "GET_USER_ROLE_API_FAIL";
export const UPDATE_ROLES_LOADER = "UPDATE_ROLES_LOADER";
export const RESET_USER_ROLES = "RESET_USER_ROLES";

