export const GET_PERMISSIONS = "GET_PERMISSIONS";
export const GET_PERMISSIONS_SUCCESS = "GET_PERMISSIONS_SUCCESS";
export const PERMISSIONS_API_FAIL = "PERMISSIONS_API_FAIL";
export const RESET_PERMISSIONS = "RESET_PERMISSIONS";
export const UPDATE_PERMISSIONS = "UPDATE_PERMISSIONS";
export const UPDATE_PERMISSIONS_SUCCESS = "UPDATE_PERMISSIONS_SUCCESS";
export const UPDATE_PERMISSIONS_LOADER = "UPDATE_PERMISSIONS_LOADER";

