export const GET_MODULE = "GET_MODULE";
export const GET_MODULE_SUCCESS = "GET_MODULE_SUCCESS";
export const MODULE_API_FAIL = "MODULE_API_FAIL";
export const RESET_MODULE = "RESET_MODULE";
export const UPDATE_MODULE_LOADER = "UPDATE_MODULE_LOADER";

