export const GET_VACCINE_TEMPLATES = "GET_VACCINE_TEMPLATES";
export const GET_VACCINE_TEMPLATES_SUCCESS = "GET_VACCINE_TEMPLATES_SUCCESS";
export const VACCINE_TEMPLATES_API_FAIL = "VACCINE_TEMPLATES_API_FAIL";
export const UPDATE_VACCINE_TEMPLATES_LOADER = "UPDATE_VACCINE_TEMPLATES_LOADER";
export const RESET_VACCINE_TEMPLATES = "RESET_VACCINE_TEMPLATES";

